# Generated by Django 3.2.25 on 2024-03-27 07:58

import audiofield.fields
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Music',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('artist', models.CharField(max_length=100)),
                ('genre', models.CharField(choices=[('Simple', 'Simple'), ('Medium', 'Medium'), ('Difficult', 'Difficult')], max_length=10)),
                ('file_upload', audiofield.fields.AudioField(upload_to='media/music/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['mp3', 'wav'])])),
                ('created', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
