# Generated by Django 3.2.25 on 2024-03-27 12:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('User', '0004_folder'),
    ]

    operations = [
        migrations.AddField(
            model_name='folder',
            name='genres',
            field=models.CharField(choices=[('rock', 'Rock'), ('pop', 'Pop'), ('hip_hop', 'Hip Hop')], default='pop', max_length=30),
        ),
    ]
