# Generated by Django 3.2.25 on 2024-03-27 12:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('User', '0005_folder_genres'),
    ]

    operations = [
        migrations.RenameField(
            model_name='folder',
            old_name='genres',
            new_name='genre',
        ),
    ]
