# Generated by Django 3.2.25 on 2024-03-27 12:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('User', '0006_rename_genres_folder_genre'),
    ]

    operations = [
        migrations.AlterField(
            model_name='folder',
            name='genre',
            field=models.CharField(choices=[('rock', 'Rock'), ('pop', 'Pop'), ('hip_hop', 'Hip Hop')], max_length=30),
        ),
    ]
