# Generated by Django 3.2.25 on 2024-03-28 05:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('User', '0008_favorite'),
    ]

    operations = [
        migrations.AddField(
            model_name='folder',
            name='is_favorites',
            field=models.BooleanField(default=False),
        ),
    ]
